weights: yolov5s.pt
cfg: "/content/drive/MyDrive/\u1103\u1175\u11B8\u1105\u1165\u1102\u1175\u11BC_\u1109\
  \u1169\u1109\u1173/yolo/yolov5/models/yolov5s.yaml"
data: "/content/drive/MyDrive/\u1103\u1175\u11B8\u1105\u1165\u1102\u1175\u11BC_\u1109\
  \u1169\u1109\u1173/yolo/data.yaml"
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 50
batch_size: 16
imgsz: 416
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: gun
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/gun2
